version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    # Of course this is only for testing on localhost
    environment:
      - DB_HOST=postgres
      - DB_USER=gin
      - DB_PASSWORD=tonic
      - DB_NAME=gin
      - GIN_MODE=release
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    # Of course this is only for testing on localhost
    environment:
      POSTGRES_USER: gin
      POSTGRES_PASSWORD: tonic
      POSTGRES_DB: gin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
