// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID           pgtype.UUID
	Name         string
	CreatedDate  pgtype.Timestamp
	StartedDate  pgtype.Timestamp
	FinishedDate pgtype.Timestamp
	Played       bool
	Finished     bool
	Description  string
	DownloadOnly bool
	Rating       pgtype.Int4
	ReleaseDate  pgtype.Date
}
