// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllGames = `-- name: GetAllGames :many
SELECT id, name, created_date, started_date, finished_date, played, finished, description, download_only, rating, release_date FROM games
`

func (q *Queries) GetAllGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.Query(ctx, getAllGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedDate,
			&i.StartedDate,
			&i.FinishedDate,
			&i.Played,
			&i.Finished,
			&i.Description,
			&i.DownloadOnly,
			&i.Rating,
			&i.ReleaseDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGame = `-- name: InsertGame :one
INSERT INTO
    games (id, name, created_date)
VALUES (uuid_generate_v4 (), $1, $2) RETURNING id, name, created_date, started_date, finished_date, played, finished, description, download_only, rating, release_date
`

type InsertGameParams struct {
	Name        string
	CreatedDate pgtype.Timestamp
}

func (q *Queries) InsertGame(ctx context.Context, arg InsertGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, insertGame, arg.Name, arg.CreatedDate)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedDate,
		&i.StartedDate,
		&i.FinishedDate,
		&i.Played,
		&i.Finished,
		&i.Description,
		&i.DownloadOnly,
		&i.Rating,
		&i.ReleaseDate,
	)
	return i, err
}
